# @package _global_
epochs: 100
num_workers: 8
batch_size: 24
shuffle: True
cuda: 0 # -1 -> no cuda otherwise takes the specified index
precompute_multi_scale: False # Compute multiscate features on cpu for faster training / inference
optim:
    base_lr: 0.001
    grad_clip: -1
    optimizer:
        class: Adam
        params:
            lr: ${training.optim.base_lr} # The path is cut from training
    lr_scheduler: 
        class: StepLR
        params:
            gamma: 0.5
            step_size: 20
weight_name: "latest" # Used during resume, select with model to load from [miou, macc, acc..., latest]
enable_cudnn: True
checkpoint_dir: ""

wandb:
    entity: ""
    project: default
    log: True
    notes:
    name:
    public: True # It will be display the model within wandb log, else not.
    config:
        model_name: ${model_name}

tensorboard:
    log: True

